#!/usr/bin/env python
'''
Purpose:    COnfig file for acquiring EO data

Version:    v1.0 (10/2021)

Author:     Ben Loveday, Plymouth Marine Laboratory
            Tim Smyth, Plymouth Marine Laboratory

License:    See LICENCE.txt
'''
import sys
import configparser
import os

# read credentials file
module_config = configparser.ConfigParser(allow_no_value=True)
module_config.read(os.path.join(os.path.expanduser("~"), '.altereco_eo.ini'))

EO_username = module_config['CREDENTIALS']['EO_username']
EO_password = module_config['CREDENTIALS']['EO_password']

# Vstep is ignored for log values
tra_config = {'CHL' : {'source':'CMEMS',
                       'local_path_root':None,
                       'nrt_product_id':'dataset-oc-glo-bio-multi-l3-chl_4km_daily-rt',
                       'dt_product_id':'dataset-oc-glo-bio-multi-l3-chl_4km_daily-rep',
                       'nrt_service_id':'OCEANCOLOUR_GLO_CHL_L3_NRT_OBSERVATIONS_009_032-TDS',
                       'dt_service_id':'OCEANCOLOUR_GLO_CHL_L3_REP_OBSERVATIONS_009_085-TDS',
                       'nrt_url_root':'http://nrt.cmems-du.eu/motu-web/Motu',
                       'dt_url_root':'http://my.cmems-du.eu/motu-web/Motu',
                       'url_template':None,
                       'depth_range':[0.493,0.4942],
                       'lat_var':'lat',
                       'lon_var':'lon',
                       't_var':'time',
                       't_ref':'1900-01-01 00:00:00',
                       't_base':'days',
                       'EO_username':EO_username,
                       'EO_password':EO_password,
                       'vars':['CHL'],
                       'calc_vars':['CHL','ZEU'],
                       'include' : True,
                       'NRT_clim' : False,
                       'clim_file' : None},

              'ADG443' : {'source':'CMEMS',
                          'local_path_root':None,
                          'nrt_product_id':'dataset-oc-atl-opt-modis_a-l3-adg443_1km_daily-rt-v02',
                          'dt_product_id':'dataset-oc-atl-opt-modis_a-l3-adg443_1km_daily-rt-v02',
                          'nrt_service_id':'OCEANCOLOUR_ATL_OPTICS_L3_NRT_OBSERVATIONS_009_034-TDS',
                          'dt_service_id':'OCEANCOLOUR_ATL_OPTICS_L3_NRT_OBSERVATIONS_009_034-TDS',
                          'nrt_url_root':'http://nrt.cmems-du.eu/motu-web/Motu',
                          'dt_url_root':'https://my.cmems-du.eu/motu-web/Motu',
                          'url_template':None,
                          'depth_range':[0.493,0.4942],
                          'lat_var':'lat',
                          'lon_var':'lon',
                          't_var':'time',
                          't_ref':'1900-01-01 00:00:00',
                          't_base':'days',
                          'EO_username':EO_username,
                          'EO_password':EO_password,
                          'vars':['ADG443'],
                          'calc_vars':['ADG443'],
                          'include' : False,
                          'NRT_clim' : False,
                          'clim_file' : None},

              'APH443' : {'source':'CMEMS',
                          'local_path_root':None,
                          'nrt_product_id':'dataset-oc-atl-opt-modis_a-l3-aph443_1km_daily-rt-v02',
                          'dt_product_id':'dataset-oc-atl-opt-modis_a-l3-aph443_1km_daily-rt-v02',
                          'nrt_service_id':'OCEANCOLOUR_ATL_OPTICS_L3_NRT_OBSERVATIONS_009_034-TDS',
                          'dt_service_id':'OCEANCOLOUR_ATL_OPTICS_L3_NRT_OBSERVATIONS_009_034-TDS',
                          'nrt_url_root':'http://nrt.cmems-du.eu/motu-web/Motu',
                          'dt_url_root':'https://my.cmems-du.eu/motu-web/Motu',
                          'url_template':None,
                          'depth_range':[0.493,0.4942],
                          'lat_var':'lat',
                          'lon_var':'lon',
                          't_var':'time',
                          't_ref':'1900-01-01 00:00:00',
                          't_base':'days',
                          'EO_username':EO_username,
                          'EO_password':EO_password,
                          'vars':['APH443'],
                          'calc_vars':['APH443'],
                          'include' : False,
                          'NRT_clim' : False,
                          'clim_file' : None},

              'ATOT443' : {'source':'CMEMS',
                           'local_path_root':None,
                           'nrt_product_id':'dataset-oc-atl-opt-modis_a-l3-atot443_1km_daily-rt-v02',
                           'dt_product_id':'dataset-oc-atl-opt-modis_a-l3-atot443_1km_daily-rt-v02',
                           'nrt_service_id':'OCEANCOLOUR_ATL_OPTICS_L3_NRT_OBSERVATIONS_009_034-TDS',
                           'dt_service_id':'OCEANCOLOUR_ATL_OPTICS_L3_NRT_OBSERVATIONS_009_034-TDS',
                           'nrt_url_root':'http://nrt.cmems-du.eu/motu-web/Motu',
                           'dt_url_root':'https://my.cmems-du.eu/motu-web/Motu',
                           'url_template':None,
                           'depth_range':[0.493,0.4942],
                           'lat_var':'lat',
                           'lon_var':'lon',
                           't_var':'time',
                           't_ref':'1900-01-01 00:00:00',
                           't_base':'days',
                           'EO_username':EO_username,
                           'EO_password':EO_password,
                           'vars':['ATOT443'],
                           'calc_vars':['ATOT443'],
                           'include' : False,
                           'NRT_clim' : False,
                           'clim_file' : None},
    
              'SST' : {'source':'CMEMS',
                       'local_path_root':None,
                       'nrt_product_id':'global-analysis-forecast-phy-001-024',
                       'dt_product_id':'cmems_mod_glo_phy_my_0.083_P1D-m',
                       'nrt_service_id':'GLOBAL_ANALYSIS_FORECAST_PHY_001_024-TDS',
                       'dt_service_id':'GLOBAL_MULTIYEAR_PHY_001_030-TDS',
                       'nrt_url_root':'http://nrt.cmems-du.eu/motu-web/Motu',
                       'dt_url_root':'https://my.cmems-du.eu/motu-web/Motu',
                       'url_template':None,
                       'depth_range':[0.493,0.4942],
                       'lat_var':'latitude',
                       'lon_var':'longitude',
                       't_var':'time',
                       't_ref':'1950-01-01 00:00:00',
                       't_base':'hours',
                       'EO_username':EO_username,
                       'EO_password':EO_password,
                       'vars':['thetao','so','mlotst'],
                       'calc_vars':['SST','SSS','MLD'],
                       'include' : True,
                       'NRT_clim' : False,
                       'clim_file' : None},

             'ALTIM': {'source':'CMEMS',
                       'local_path_root':None,
                       'nrt_product_id': 'dataset-duacs-nrt-global-merged-allsat-phy-l4',
                       'dt_product_id': 'cmems_obs-sl_glo_phy-ssh_my_allsat-l4-duacs-0.25deg_P1D',
                       'nrt_service_id':'SEALEVEL_GLO_PHY_L4_NRT_OBSERVATIONS_008_046-TDS',
                       'dt_service_id':'SEALEVEL_GLO_PHY_L4_MY_008_047-TDS',
                       'nrt_url_root':'http://nrt.cmems-du.eu/motu-web/Motu',
                       'dt_url_root':'http://my.cmems-du.eu/motu-web/Motu',
                       'url_template':None,
                       'depth_range':[0.493,0.4942],
                       'lat_var':'latitude',
                       'lon_var':'longitude',
                       't_var':'time',
                       't_ref':'1950-01-01 00:00:00',
                       't_base':'days',
                       'EO_username':EO_username,
                       'EO_password':EO_password,
                       'vars':['sla','adt','ugos','vgos','ugosa','vgosa'],
                       'calc_vars':['UGOS','VGOS','UGOSA','VGOSA','SLA','ADT','EKE','MKE','TKE'],
                       'include' : True,
                       'NRT_clim' : False,
                       'clim_file' : None},

              'PAR' : {'source':'MODIS',
                       'local_path_root':None,
                       'path_suffix':None,
                       'nrt_url_root':'https://oceandata.sci.gsfc.nasa.gov/opendap/hyrax/MODISA/L3SMI/',
                       'dt_url_root':'https://oceandata.sci.gsfc.nasa.gov/opendap/hyrax/MODISA/L3SMI/',
                       'url_template':'$Y/$j/A$Y$j.L3m_DAY_PAR_par_4km.nc.nc',
                       'lat_var':'lat',
                       'lon_var':'lon',
                       't_var':'time',
                       't_ref':'2000-01-01 00:00:00',
                       't_base':'seconds',
                       'vars':['par'],
                       'calc_vars':['PAR'],
                       'include' : True,
                       'NRT_clim' : False,
                       'clim_file' : None},

              'KD490': {'source':'MODIS',
                        'local_path_root':None,
                        'path_suffix':None,
                        'nrt_url_root':'https://oceandata.sci.gsfc.nasa.gov/opendap/hyrax/MODISA/L3SMI/',
                        'dt_url_root':'https://oceandata.sci.gsfc.nasa.gov/opendap/hyrax/MODISA/L3SMI/',
                        'url_template':'$Y/$j/A$Y$j.L3m_DAY_KD490_Kd_490_4km.nc.nc',
                        'lat_var':'lat',
                        'lon_var':'lon',
                        't_var':'time',
                        't_ref':'2000-01-01 00:00:00',
                        't_base':'seconds',
                        'vars':['Kd_490'],
                        'calc_vars':['KD490'],
                        'include' : True,
                        'NRT_clim' : False,
                        'clim_file' : None},

             'ATMOS': {'source':'ECMWF',
                       'local_path_root':None,
                       'path_suffix':None,
                       'url_root':None,
                       'url_template':None,
                       'lat_var':'latitude',
                       'lon_var':'longitude',
                       't_var':'time',
                       't_ref':'1900-01-01 00:00:00',
                       't_base':'hours',
                       'vars':['u10','v10','tcc','msl','tco3','tcwv','t2m','d2m'],
                       'calc_vars':['WSPD','CLOUD','MSLP','O3','TCWV','RH'],
                       'include' : True,
                       'NRT_clim' : True,
                       'clim_file' : '/home/ben/shared/Linux_desktop/data/datasets/Projects/AlterEco/Climatologies/ECMWF_ERA_I/ERAI_monthly_climatology.nc'},

             }
#EOF
